config/routes.rb
Kloudcatch::Application.routes.draw do
  resources :droplets
  get '/synch/:id' => 'droplets#synch'
  get '/confirm/:id' => 'droplets#confirm'
  get '/pending' => 'droplets#pending'
  post '/upload' => 'droplets#upload'
  
  match '/subscribe' => 'users#subscribe', :via => :post
  match '/unsubscribe' => 'users#unsubscribe', :via => :delete

  match '/login' => 'sessions#login'
  match '/logout' => 'sessions#logout'
end

app/models/droplet.rb
class Droplet < ActiveRecord::Base
  belongs_to :user
  belongs_to :status
  has_many :droplet_histories
    
  after_save :update_history
  
  def download
    dir = File.join(Configuration::DOWNLOAD_PATH, user.email)
	FileUtils.makedirs(dir)
    update_status("downloading")
    self.name, self.file = EngineFactory.get(url).download(url, dir)
	update_status("downloaded")
  rescue
    update_status("pending")
  end
  
  def upload(name, data)
	dir = File.join(Configuration::DOWNLOAD_PATH, user.email)
	FileUtils.makedirs(dir)
	self.name = name
	self.file = File.join(dir, name)
	File.open(self.file, 'wb' ) do |file|
	  file.write(data.read)
    end
  end
  
  def update_status(name)
    self.status_id = Status.find_by_name(name).id
	save
  end
  
  private
  def update_history
    DropletHistory.create!(:droplet => self, :status => status, :user => user)
  end
  
end

app/controllers/droplets_controller.rb
class DropletsController < ApplicationController
  
  # GET /droplets
  # GET /droplets.json
  def index
    @droplets = Droplet.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @droplets }
    end
  end

  # GET /droplets/1
  # GET /droplets/1.json
  def show
    @droplet = Droplet.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @droplet }
    end
  end

  # GET /droplets/new
  # GET /droplets/new.json
  def new
    @droplet = Droplet.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @droplet }
    end
  end

  # GET /droplets/1/edit
  def edit
    @droplet = Droplet.find(params[:id])
  end

  # POST /droplets
  # POST /droplets.json
  def create
    @droplet = Droplet.new(params[:droplet])
    @droplet.user ||= current_user
    @droplet.status ||= Status.find_by_name("pending")

    respond_to do |format|
      if @droplet.save
        format.html { redirect_to @droplet, notice: 'Droplet was successfully created.' }
        format.json { render json: @droplet, status: :created, location: @droplet }
      else
        format.html { render action: "new" }
        format.json { render json: @droplet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /droplets/1
  # PUT /droplets/1.json
  def update
    @droplet = Droplet.find(params[:id])
	@droplet.user ||= current_user

    respond_to do |format|
      if @droplet.update_attributes(params[:droplet])
        format.html { redirect_to @droplet, notice: 'Droplet was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @droplet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /droplets/1
  # DELETE /droplets/1.json
  def destroy
    @droplet = Droplet.find(params[:id])
	@droplet.user = current_user
    @droplet.status = Status.find_by_name("removed")
    @droplet.save

    respond_to do |format|
      format.html { redirect_to droplets_url }
      format.json { head :ok }
    end
  end
  
  def pending
    downloaded_id = Status.find_by_name("downloaded").id
	synched_id = Status.find_by_name("synched").id
    droplets = Droplet.select([:id, :name]).where(:status_id => [downloaded_id, synched_id], :user_id => current_user.id).all
	render :json => {:droplets => droplets}.to_json
  rescue
    render :text => "error"
  end
  
  def synch
	downloaded_id = Status.find_by_name("downloaded").id
	synched_id = Status.find_by_name("synched").id
    droplet = Droplet.where(:id => params[:id], :user_id => current_user.id, :status_id => [downloaded_id, synched_id]).first
	raise if droplet.nil?
	droplet.update_status("synched")
	send_file droplet.file, :x_sendfile=>true
  rescue
    render :text => "error"
  end
  
  def confirm
    droplet = Droplet.where(:id => params[:id], :user_id => current_user.id, :status_id => Status.find_by_name("synched").id).first
	raise if droplet.nil?
	droplet.update_status("removed")
	File.delete(droplet.file)
	droplet.file = ""
	render :text => "ok"
  rescue
    render :text => "error"
  end
  
  def upload
	@droplet = Droplet.new()
    @droplet.user = current_user
	if params.has_key? :force
		params.each{|param| @file = param[1] if param[1].is_a? ActionDispatch::Http::UploadedFile }
		@droplet.upload(params[:name], @file)
	else
		@droplet.upload(params[:name], params[:data])
	end
	@droplet.status = Status.find_by_name("downloaded")
	render :text => "ok"
  rescue
    render :text => "error"
  end
  
end

app/helpers/droplets_helper.rb
module DropletsHelper
end

app/views/droplets/_form.html.erb
<%= form_for(@droplet) do |f| %>
  <% if @droplet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@droplet.errors.count, "error") %> prohibited this droplet from being saved:</h2>

      <ul>
      <% @droplet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :user %><br />
    <%= f.text_field :user %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/droplets/edit.html.erb
<h1>Editing droplet</h1>

<%= render 'form' %>

<%= link_to 'Show', @droplet %> |
<%= link_to 'Back', droplets_path %>

app/views/droplets/index.html.erb
<h1>Listing droplets</h1>

<table>
  <tr>
    <th>Url</th>
    <th>Status</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @droplets.each do |droplet| %>
  <tr>
    <td><%= droplet.url %></td>
    <td><%= droplet.status %></td>
    <td><%= droplet.user %></td>
    <td><%= link_to 'Show', droplet %></td>
    <td><%= link_to 'Edit', edit_droplet_path(droplet) %></td>
    <td><%= link_to 'Destroy', droplet, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Droplet', new_droplet_path %>

app/views/droplets/new.html.erb
<h1>New droplet</h1>

<%= render 'form' %>

<%= link_to 'Back', droplets_path %>

app/views/droplets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Url:</b>
  <%= @droplet.url %>
</p>

<p>
  <b>Status:</b>
  <%= @droplet.status %>
</p>

<p>
  <b>User:</b>
  <%= @droplet.user %>
</p>


<%= link_to 'Edit', edit_droplet_path(@droplet) %> |
<%= link_to 'Back', droplets_path %>